- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Use the built-in functionality in the `go` command to extract the
current module version in the issue template instructions, rather than
relying on `jq` parsing.
> Don't rely on jq in issue template.

- schema_server.go
- schema_server_test.go
Allow schemas to differ in the order of attributes if they are otherwise
identical. Applies to the checks on provider schemas and provider_meta
schemas to ensure the servers are in agreement.
Fixes #16.
> Be more permissive when checking schemas are identical.

- go.mod
- go.sum
- schema_server_test.go
closes #20 
Tested with a version of terraform-plugin-corner upgraded to plugin-go v0.3.0.
> plugin-go v0.3.0

- internal/logging/context.go
- internal/logging/doc.go
- internal/logging/environment_variables.go
- internal/logging/keys.go
- internal/logging/mux.go
- schema_server.go
Reference: https://github.com/hashicorp/terraform-plugin-mux/issues/19
Reference: https://github.com/hashicorp/terraform-plugin-mux/issues/33
In the near future, this project will be implementing multiple packages which will be reliant on shared logging details. Refactoring this code now will prevent duplication when those packages get created.
This logging package structure is similar to what is being implemented in terraform-plugin-go, not only for code consistency, but in the event that portions or all of this project is subsumed into that project.
> Refactor logging into shared internal package

- .github/CONTRIBUTING.md
Reference: https://github.com/hashicorp/terraform-plugin-framework/pull/254
Copied as the Terraform Plugin projects should all share the same documentation and processes.
> Update Contributing Guide with Changelog and Dependency Update information

- .changelog/42.txt
- README.md
- internal/tf5testserver/tf5testserver.go
- internal/tf6testserver/tf6testserver.go
- internal/tfprotov5tov6/tfprotov5tov6.go
- internal/tfprotov5tov6/tfprotov5tov6_test.go
- internal/tfprotov6tov5/tfprotov6tov5.go
- internal/tfprotov6tov5/tfprotov6tov5_test.go
- tf5to6server/tf5to6server.go
- tf5to6server/tf5to6server_test.go
- tf6to5server/tf6to5server.go
- tf6to5server/tf6to5server_test.go
Closes #33
These packages handle upgrading and downgrading protocol servers. This enables additional provider combinations, such as terraform-plugin-sdk/v2 and terraform-plugin-framework.
> Introduce tf5to6server and tf6to5server packages

- tf5muxserver/doc.go
- tf5to6server/doc.go
- tf6muxserver/doc.go
- tf6to5server/doc.go
* Minor godoc formatting fix
* Added links that point to the actual pkg.go.dev pages of the referenced types/structs
* To appease my IDE, I have also changed slightly the first line to start with `Package X...`: I suspect that with the right linter, this would have been picked up
> Fixing the formatting of the generated godoc for the 4 key packages of this library

- tf5muxserver/doc.go
- tf5muxserver/mux_server.go
- tf5to6server/doc.go
- tf6muxserver/doc.go
- tf6muxserver/mux_server.go
- tf6to5server/doc.go
- tf6to5server/tf6to5server.go
To prevent issues with the latest `golangci-lint` in CI.
> all: Run Go 1.19 fmt

- .changelog/118.txt
- tf5muxserver/mux_server_test.go
- tf5muxserver/schema_equality.go
- tf6muxserver/mux_server_test.go
- tf6muxserver/schema_equality.go
- website/docs/plugin/mux/combining-protocol-version-5-providers.mdx
> Ignore MinItems and MaxItems diff in nested block

- .golangci.yml
- tf5muxserver/mux_server_ApplyResourceChange_test.go
- tf5muxserver/mux_server_ConfigureProvider_test.go
- tf5muxserver/mux_server_ImportResourceState_test.go
- tf5muxserver/mux_server_PlanResourceChange_test.go
- tf5muxserver/mux_server_PrepareProviderConfig_test.go
- tf5muxserver/mux_server_ReadDataSource_test.go
- tf5muxserver/mux_server_ReadResource_test.go
- tf5muxserver/mux_server_StopProvider_test.go
- tf5muxserver/mux_server_UpgradeResourceState_test.go
- tf5muxserver/mux_server_ValidateDataSourceConfig_test.go
- tf5muxserver/mux_server_ValidateResourceTypeConfig_test.go
- tf6muxserver/mux_server_ApplyResourceChange_test.go
- tf6muxserver/mux_server_ConfigureProvider_test.go
- tf6muxserver/mux_server_ImportResourceState_test.go
- tf6muxserver/mux_server_PlanResourceChange_test.go
- tf6muxserver/mux_server_ReadDataSource_test.go
- tf6muxserver/mux_server_ReadResource_test.go
- tf6muxserver/mux_server_StopProvider_test.go
- tf6muxserver/mux_server_UpgradeResourceState_test.go
- tf6muxserver/mux_server_ValidateDataResourceConfig_test.go
- tf6muxserver/mux_server_ValidateProviderConfig_test.go
- tf6muxserver/mux_server_ValidateResourceConfig_test.go
contributes to: https://github.com/hashicorp/terraform-providers-devex-internal/issues/102 + https://github.com/hashicorp/terraform-providers-devex-internal/issues/83
- `deadcode` and `varcheck` linters are deprecated in **golangci-lint** in favor of `unused`
```bash
$ golangci-lint run
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
```
> ci: added `forcetypeassert` and `misspell` lint rules

- website/docs/plugin/mux/combining-protocol-version-5-providers.mdx
- website/docs/plugin/mux/combining-protocol-version-6-providers.mdx
- website/docs/plugin/mux/index.mdx
- website/docs/plugin/mux/translating-protocol-version-5-to-6.mdx
- website/docs/plugin/mux/translating-protocol-version-6-to-5.mdx
- Migrates the formats of links in Markdown content as part of the [Docs Content Link Rewrites project](https://docs.google.com/document/d/1WaSyvoVPS-YCNiSPX0ynGpvc1gySEcpbrRoQVhimQCA/edit)
These are all the links that were determined to be "unrewriteable" (AKA no rewrite needed to be applied based on the rewrite script's logic):
<details>
<summary>🌟 Expand for lists of links by file name</summary>
```JSON
{
"website/docs/plugin/mux/combining-protocol-version-5-providers.mdx": [
"https://pkg.go.dev/github.com/hashicorp/terraform-plugin-mux/tf5muxserver",
"https://pkg.go.dev/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server",
"https://pkg.go.dev/github.com/hashicorp/terraform-plugin-mux/tf5muxserver#NewMuxServer",
"#testing-implementation", …
```
> docs: Migrate link formats

- .github/workflows/ci-github-actions.yml
- .github/workflows/ci-go.yml
- .github/workflows/ci-goreleaser.yml
- .github/workflows/release.yml
> Not a bot 🤖 - #145 had some problems with the comments, maybe because of the old `@v2` in there 🤷🏻 
Bumps [actions/checkout](https://github.com/actions/checkout) to 3.4.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/actions/checkout/releases">actions/checkout's releases</a>.</em></p>
<blockquote>
<h2>v3.0.0</h2>
<ul>
<li>Updated to the node16 runtime by default
<ul>
<li>This requires a minimum <a href="https://github.com/actions/runner/releases/tag/v2.285.0">Actions Runner</a> version of v2.285.0 to run, which is by default available in GHES 3.4 or later.</li>
</ul>
</li>
</ul>
<h2>v2.6.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Add backports to v2 branch by <a href="https://github.com/cory-miller"><code>@​cory-miller</code></a> in <a …
> Bump actions/checkout to 3.4.0

- .changes/unreleased/BUG FIXES-20230421-133145.yaml
- tf5muxserver/mux_server_GetProviderSchema.go
- tf5muxserver/mux_server_GetProviderSchema_test.go
- tf6muxserver/mux_server_GetProviderSchema.go
- tf6muxserver/mux_server_GetProviderSchema_test.go
> tf5muxserver+tf6muxserver: Ensure mux server errors in `GetProviderSchema` response set error severity in diagnostics

- website/docs/plugin/mux/combining-protocol-version-5-providers.mdx
- website/docs/plugin/mux/combining-protocol-version-6-providers.mdx
- website/docs/plugin/mux/translating-protocol-version-5-to-6.mdx
- website/docs/plugin/mux/translating-protocol-version-6-to-5.mdx
Reference: https://discuss.hashicorp.com/t/terraform-framework-migration-testing/55744/2
Since this documentation was introduced, the terraform-plugin-testing Go module and its associated https://developer.hashicorp/terraform/plugin/testing documentation were released. The prior documentation made it sound like sdk/v2-based acceptance testing was required while either testing setup can be used.
> docs: Remove errant sdk/v2 specifics

- internal/tf5testserver/tf5testserver.go
- internal/tf6testserver/tf6testserver.go
- tf5muxserver/mux_server_ConfigureProvider_test.go
- tf5muxserver/mux_server_GetProviderSchema_test.go
- tf5muxserver/mux_server_PrepareProviderConfig_test.go
- tf5muxserver/mux_server_StopProvider_test.go
- tf6muxserver/mux_server_ConfigureProvider_test.go
- tf6muxserver/mux_server_GetProviderSchema_test.go
- tf6muxserver/mux_server_StopProvider_test.go
- tf6muxserver/mux_server_ValidateProviderConfig_test.go
This PR adds the return of an empty `GetProviderSchemaResponse{}` when the `TestServer.GetProviderSchemaResponse` is nil:
```go
func (s *TestServer) GetProviderSchema(_ context.Context, _ *tfprotov5.GetProviderSchemaRequest) (*tfprotov5.GetProviderSchemaResponse, error) {
s.GetProviderSchemaCalled = true
if s.GetProviderSchemaResponse != nil {
return s.GetProviderSchemaResponse, nil
}
return &tfprotov5.GetProviderSchemaResponse{}, nil
}
```
Equivalent code changes have been made in both _tf5testserver.go_ and _tf6testserver.go_.
This allows the code to be DRY-ed up by removing the need to define an empty `GetProviderSchemaResponse` in all places in which `TestServer.GetProviderSchema()` is called and an empty `GetProviderSchemaResponse` is required.
> DRY-up usage of GetProviderSchemaResponse

- .github/dependabot.yml
This Go module should only be upgraded via terraform-plugin-go upgrades of the dependency.
Similar to https://github.com/hashicorp/terraform-plugin-go/blob/61e2b51627723cd1913a8b01b8cc730e99cd30d1/.github/dependabot.yml#L5-L7
> deps: Ignore google.golang.org/grpc direct updates in Dependabot

- .changes/unreleased/FEATURES-20240126-143840.yaml
- internal/tf5testserver/tf5testserver.go
- internal/tf6testserver/tf6testserver.go
- internal/tfprotov5tov6/tfprotov5tov6.go
- internal/tfprotov5tov6/tfprotov5tov6_test.go
- internal/tfprotov6tov5/tfprotov6tov5.go
- internal/tfprotov6tov5/tfprotov6tov5_test.go
- tf5muxserver/mux_server.go
- tf5muxserver/mux_server_GetMetadata_test.go
- tf5muxserver/mux_server_GetProviderSchema_test.go
- tf5muxserver/mux_server_MoveResourceState.go
- tf5muxserver/mux_server_MoveResourceState_test.go
- tf5muxserver/server_capabilities.go
- tf5to6server/tf5to6server.go
- tf5to6server/tf5to6server_test.go
- tf6muxserver/mux_server.go
- tf6muxserver/mux_server_GetMetadata_test.go
- tf6muxserver/mux_server_GetProviderSchema_test.go
- tf6muxserver/mux_server_MoveResourceState.go
- tf6muxserver/mux_server_MoveResourceState_test.go
- tf6muxserver/server_capabilities.go
- tf6to5server/tf6to5server.go
- tf6to5server/tf6to5server_test.go
Reference: https://github.com/hashicorp/terraform-plugin-go/pull/364
The next versions of the plugin protocol (5.5/6.5) include support for the MoveResourceState RPC and server capability. This change includes initial implementation of the new RPC in all server implementations.
> all: Initial MoveResourceState implementations

- .changes/unreleased/NOTES-20240229-144205.yaml
- .github/workflows/ci-go.yml
- README.md
- go.mod
- tools/go.mod
- tools/go.sum
Reference: https://github.com/hashicorp/terraform-providers-devex-internal/issues/175
- Adding a change log entry for the bump to Go `1.21`.
- Reinstating the `go toolchain` directive in `go.mod`.
- Updating CI and docs to reflect update to Go `1.21`.
> Reinstate go toolchain and add changelog for Go version bump to 1.21

- .changes/unreleased/ENHANCEMENTS-20240507-180758.yaml
- .changes/unreleased/ENHANCEMENTS-20240507-180817.yaml
- internal/tfprotov5tov6/tfprotov5tov6.go
- internal/tfprotov5tov6/tfprotov5tov6_test.go
- internal/tfprotov6tov5/tfprotov6tov5.go
- internal/tfprotov6tov5/tfprotov6tov5_test.go
Ref: https://github.com/hashicorp/terraform-plugin-go/pull/403
Adds the new request fields and response fields to support deferred actions.
> all: Update tfproto translation servers to support deferred actions

- tf5muxserver/mux_server.go
- tf5muxserver/mux_server_CallFunction.go
- tf5muxserver/mux_server_CallFunction_test.go
- tf5muxserver/mux_server_GetFunctions.go
- tf5muxserver/mux_server_GetFunctions_test.go
- tf5muxserver/mux_server_MoveResourceState.go
- tf5muxserver/mux_server_MoveResourceState_test.go
- tf5muxserver/mux_server_test.go
- tf5to6server/tf5to6server.go
- tf5to6server/tf5to6server_test.go
- tf6muxserver/mux_server.go
- tf6muxserver/mux_server_CallFunction.go
- tf6muxserver/mux_server_CallFunction_test.go
- tf6muxserver/mux_server_GetFunctions.go
- tf6muxserver/mux_server_GetFunctions_test.go
- tf6muxserver/mux_server_MoveResourceState.go
- tf6muxserver/mux_server_MoveResourceState_test.go
- tf6muxserver/mux_server_test.go
- tf6to5server/tf6to5server.go
- tf6to5server/tf6to5server_test.go
Closes #210 
Closes #219 
With the release of `terraform-plugin-go` [v0.23.0](https://github.com/hashicorp/terraform-plugin-go/releases/tag/v0.23.0), the `FunctionServer` interface and `MoveResourceState` method are now required. This PR removes the temporary type assertions.
I'm not sure if this warrants a changelog, but happy to add a `NOTE` if we think it's helpful.
> all: Remove type assertions for Function and MoveResourceState RPC implementations

- .changes/unreleased/NOTES-20240906-165503.yaml
- .github/workflows/ci-go.yml
- .golangci.yml
- README.md
- go.mod
- tools/go.mod
Ref: https://github.com/hashicorp/terraform-providers-devex-internal/issues/182
Bumps the minimum Go module to 1.22.0 to allow for all patch versions in 1.22. Toolchain is using the latest 1.22.7
> all: Bump minimum Go module version to 1.22

- internal/tfprotov5tov6/tfprotov5tov6.go
- internal/tfprotov6tov5/tfprotov6tov5.go
- tf5muxserver/mux_server_GetMetadata_test.go
- tf5muxserver/mux_server_GetProviderSchema_test.go
- tf6muxserver/mux_server_GetMetadata_test.go
This isn't actually fixing a bug, since muxed servers always return all client capabilities as true, but just for completeness since I was in the neighborhood 😆 
No changelog or release for this one
> internal: Add MoveResourceState capability to mux translations

- website/README.md
- website/docs/plugin/mux/combining-protocol-version-5-providers.mdx
- website/docs/plugin/mux/combining-protocol-version-6-providers.mdx
- website/docs/plugin/mux/index.mdx
- website/docs/plugin/mux/translating-protocol-version-5-to-6.mdx
- website/docs/plugin/mux/translating-protocol-version-6-to-5.mdx
We are migrating the terraform-plugin-* documentation to a unified HashiCorp product documentation repository. As a result of this migration, the unified repo (web-unified-docs) will be the source of truth.
This PR adds a noticed to all existing MDX files in the original location so folks know where to contribute. We plan on deprecating and removing the files in /website.
This PR will be merged after docs have been migrated
> Add comments for UDR migration

- .github/workflows/ci-go.yml
Previously, it was just using running a single test with the latest Terraform version that is installed on the machine.
It also adds both protov5 + protov6 runs, and the explicit targeting of the mux packages
> chore: Add explicit terraform installation for tests

- .goreleaser.yml
- go.mod
- go.sum
This PR updates the dependency to the pre-release for plugin-go that supports resource identity, which will be the last PR to prep for a `terraform-plugin-mux@v0.19.0-alpha.1` pre-release.
It also includes a modification to the goreleaser file which I believe should automatically handle the GitHub release portion: https://goreleaser.com/customization/release/#github
It's not immediately clear from the documentation that if the pre-release is detected, that it will not mark it as latest, but the GitHub UI doesn't even let you do that.... so hopefully that works! 🤞🏻
> chore: Update to use plugin-go alpha1 + allow goreleaser to handle pre-releases

- .changes/unreleased/BUG FIXES-20250521-151305.yaml
- go.mod
- go.sum
- tf5muxserver/mux_server_GetResourceIdentitySchemas.go
- tf5muxserver/mux_server_GetResourceIdentitySchemas_test.go
- tf5muxserver/mux_server_UpgradeResourceIdentity.go
- tf5muxserver/mux_server_UpgradeResourceIdentity_test.go
- tf5to6server/tf5to6server.go
- tf5to6server/tf5to6server_test.go
- tf6muxserver/mux_server_GetResourceIdentitySchemas.go
- tf6muxserver/mux_server_GetResourceIdentitySchemas_test.go
- tf6muxserver/mux_server_UpgradeResourceIdentity.go
- tf6muxserver/mux_server_UpgradeResourceIdentity_test.go
- tf6to5server/tf6to5server.go
- tf6to5server/tf6to5server_test.go
Closes #279 
Ref: https://github.com/hashicorp/terraform-plugin-go/pull/516
This removes the temporary interface that is removed in `terraform-plugin-go@v0.28.0`
N/A
> Update `terraform-plugin-go` and add changelogs for `v0.20.0` release

- internal/tfprotov5tov6/tfprotov5tov6.go
- internal/tfprotov6tov5/tfprotov6tov5.go
- tf5muxserver/mux_server_GetMetadata_test.go
- tf5muxserver/mux_server_GetProviderSchema_test.go
- tf5muxserver/mux_server_ValidateListResourceConfig.go
- tf5to6server/tf5to6server_test.go
- tf6muxserver/mux_server_GetMetadata.go
- tf6muxserver/mux_server_GetMetadata_test.go
- tf6muxserver/mux_server_GetProviderSchema.go
- tf6muxserver/mux_server_GetProviderSchema_test.go
- tf6muxserver/mux_server_ValidateListResourceConfig.go
- tf6to5server/tf6to5server_test.go
Addresses comments from #310
Fixes some naming and adds testing to ValidateListResourceConfig RFC
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
No
> Addressed comments in previous PR #310

- go.mod
- go.sum
- internal/tf5testserver/tf5testserver.go
- internal/tf6testserver/tf6testserver.go
- internal/tfprotov5tov6/tfprotov5tov6.go
- internal/tfprotov5tov6/tfprotov5tov6_test.go
- internal/tfprotov6tov5/tfprotov6tov5.go
- internal/tfprotov6tov5/tfprotov6tov5_test.go
- tf5muxserver/mux_server_ValidateActionConfig.go
- tf5muxserver/mux_server_ValidateActionConfig_test.go
- tf5to6server/tf5to6server.go
- tf5to6server/tf5to6server_test.go
- tf6muxserver/mux_server_ValidateActionConfig.go
- tf6muxserver/mux_server_ValidateActionConfig_test.go
- tf6to5server/tf6to5server.go
- tf6to5server/tf6to5server_test.go
Ref: https://github.com/hashicorp/terraform-plugin-go/pull/539
This PR adds the `ValidateActionConfig` RPC to all of the mux server implementations, see https://github.com/hashicorp/terraform-plugin-go/pull/539
No
> all: Add `ValidateActionConfig` RPC implementation to mux servers
